import { useEffect, useMemo, useState } from 'react';
import { LanguageContext } from './language';

const dictionaries = {
  fr: {
    home: 'Accueil',
    shop: 'Shop',
    about: 'A propos',
    contact: 'Contact',
    admin: 'Admin',
    cameras: 'Cameras',
    accessories: 'Accessoires',
    laptop: 'Laptop',
    searchPlaceholder: 'Rechercher...',
    noSearchResults: 'Aucun resultat',
    viewAllResults: 'Voir tous les resultats',
    heroTitle: 'The Phone House  - Phones and Accessories',
    heroText:
      'Decouvrez du materiel professionnel haut de gamme pour capturer chaque moment.',
    buy: 'Acheter',
    moreInfo: "Plus d'informations",
    ourProducts: 'Nos Produits',
    featured: 'Produits a la une',
    promotions: 'Promotions',
    new: 'Nouveau',
    add: 'Ajouter',
    addToCart: 'Ajouter au panier',
    addedToCart: 'Produit ajoute au panier',
    addedToWishlist: 'Ajoute aux favoris',
    removedFromWishlist: 'Retire des favoris',
    catalog: 'Catalogue',
    catalogTitle: 'Materiel photo premium',
    productCount: 'produit(s)',
    searchProduct: 'Rechercher un produit...',
    allCategories: 'Toutes les categories',
    allBrands: 'Toutes les marques',
    sortBy: 'Trier par',
    priceLowHigh: 'Prix: bas vers haut',
    priceHighLow: 'Prix: haut vers bas',
    noProducts: 'Aucun produit trouve',
    noProductsText: 'Essayez une autre recherche ou changez les filtres.',
    relatedProducts: 'Produits similaires',
    productNotFound: 'Produit introuvable',
    backToCatalog: 'Retour au catalogue',
    cart: 'Panier',
    cartEmpty: 'Votre panier est vide',
    cartEmptyText: 'Ajoutez vos cameras, laptops et accessoires favoris.',
    viewCatalog: 'Voir le catalogue',
    checkoutTitle: 'Finaliser la commande',
    clearCart: 'Vider le panier',
    summary: 'Resume',
    subtotal: 'Sous-total',
    delivery: 'Livraison',
    toConfirm: 'A confirmer',
    total: 'Total',
    requestOrder: 'Demander la commande',
    confirmClearTitle: 'Vider le panier ?',
    confirmClearMessage: 'Tous les produits seront retires de votre panier.',
    confirmOrderTitle: 'Confirmer la commande ?',
    confirmOrderMessage: 'Voulez-vous valider cette commande ?',
    orderCreated: 'Commande creee',
    orderCreatedMessage: 'Votre commande a ete enregistree avec succes.',
    confirmRemoveTitle: 'Supprimer ce produit ?',
    remove: 'Supprimer',
    cancel: 'Annuler',
    clearedCart: 'Panier vide',
    removedProduct: 'Produit retire',
    wishlist: 'Favoris',
    wishlistEmpty: 'Aucun favori pour le moment',
    wishlistEmptyText:
      'Gardez vos produits preferes ici pour les retrouver rapidement.',
    exploreProducts: 'Explorer les produits',
    wishlistTitle: 'Votre selection',
    aboutTitle: 'Un store pour createurs exigeants',
    selectionPremium: 'Selection premium',
    selectionText:
      'The Phone House met en avant des telephones, accessoires et laptops choisis pour la creation photo et video.',
    localBase: 'Base en Algerie',
    localText:
      "L'equipe accompagne les clients depuis Bordj Bou Arreridj avec une approche simple, directe et locale.",
    usefulAdvice: 'Conseil utile',
    usefulAdviceText:
      'Besoin de choisir entre deux modeles ? Le support vous aide a trouver le materiel adapte a votre usage.',
    contactTitle: 'Parlez-nous de votre besoin',
    address: 'Adresse',
    addressText:
      'Bordj Bou Arreridj, Algerie. Livraison disponible selon la commande.',
    support: 'Support',
    supportText:
      'Assistance 7j/7 pour les demandes produit, disponibilites et commandes.',
    quickRequest: 'Demande rapide',
    name: 'Nom',
    phoneOrEmail: 'Telephone ou email',
    message: 'Votre message',
    send: 'Envoyer',
    messagePrepared: 'Message envoye',
    messagePreparedText: 'Votre message a ete livre avec succes. Nous le traiterons des que possible. Merci.',
    pageNotFound: 'Page introuvable',
    pageNotFoundText: "Cette page n'existe pas ou a ete deplacee.",
    backHome: "Retour a l'accueil",
    footerText:
      'Votre destination pour les meilleurs produits photo, laptops et accessoires de creation.',
    navigation: 'Navigation',
    quickLinks: 'Liens rapides',
    products: 'Produits',
    rights: '2026 The Phone House. Tous droits reserves.',
    deliveryTitle: 'Livraison',
    deliveryText: 'Livraison rapide partout en Algerie',
    location: 'Localisation',
    supportClient: 'Support client',
    securePayment: 'Paiement securise',
    securePaymentText: 'Transactions fiables et suivi de commande',
    adminTitle: 'Dashboard admin',
    adminSubtitle: 'Gerez les produits, promotions et statistiques du store.',
    adminLogin: 'Connexion admin',
    adminLoginText: 'Acces reserve a la gestion du store.',
    username: 'Utilisateur',
    password: 'Mot de passe',
    login: 'Connexion',
    logout: 'Deconnexion',
    invalidCredentials: 'Identifiants incorrects',
    signedIn: 'Connexion reussie',
    backToStore: 'Voir le store',
    adminEssential: 'Back office',
    charts: 'Statistiques visuelles',
    categoryDistribution: 'Produits par categorie',
    promotionShare: 'Etat des promotions',
    uploadImage: 'Uploader image',
    uploadSecondImage: 'Uploader image 2',
    activePromos: 'Promos actives',
    normalProducts: 'Produits standards',
    totalProducts: 'Produits',
    promoProducts: 'Promotions',
    categoriesStat: 'Categories',
    inventoryValue: 'Valeur catalogue',
    productManager: 'Gestion des produits',
    addProduct: 'Ajouter un produit',
    updateProduct: 'Mettre a jour',
    resetForm: 'Reinitialiser',
    brand: 'Marque',
    category: 'Categorie',
    price: 'Prix',
    rating: 'Note',
    image: 'Image',
    secondImage: 'Image 2',
    description: 'Description',
    isNew: 'Nouveau',
    isPromo: 'Promotion',
    discount: 'Reduction %',
    actions: 'Actions',
    edit: 'Modifier',
    promo: 'Promo',
    productSaved: 'Produit enregistre',
    productDeleted: 'Produit supprime',
    confirmDeleteProduct: 'Supprimer ce produit ?',
    confirmDeleteProductText: 'Il disparaitra du catalogue public.',
    promotionUpdated: 'Promotion mise a jour',
    shareExperience: 'Partagez votre experience',
    personalInfo: 'Informations personnelles',
    firstName: 'Prenom',
    lastName: 'Nom de famille',
    phone: 'Telephone',
    emailOptional: 'Email (optionnel)',
    shippingAddress: 'Adresse de livraison',
    wilaya: 'Wilaya',
    selectWilaya: 'Selectionner une wilaya',
    baladiya: 'Commune (Baladiya)',
    selectBaladiya: 'Selectionner une commune',
    fullAddress: 'Adresse complete',
    postalCode: 'Code postal (optionnel)',
    orderDetails: 'Details de la commande',
    quantity: 'Quantite',
    additionalNotes: 'Notes additionnelles',
    placeOrder: 'Passer la commande',
    fieldRequired: 'Ce champ est requis',
    invalidPhone: 'Numero de telephone invalide',
    invalidEmail: 'Adresse email invalide',
    orders: 'Commandes',
    totalOrders: 'Total Commandes',
    totalRevenue: 'Revenu Total',
    averageOrderValue: 'Panier Moyen',
    pendingOrders: 'Commandes en attente',
    ordersByWilaya: 'Commandes par Wilaya',
    ordersByProduct: 'Commandes par Produit',
    monthlySales: 'Ventes Mensuelles',
    orderStatusDistribution: 'Statuts des Commandes',
    topSellingProducts: 'Meilleures Ventes',
    revenueByDay: 'Revenu par Jour',
    searchOrders: 'Rechercher une commande...',
    status: 'Statut',
    orderDate: 'Date',
    customer: 'Client',
    allStatuses: 'Tous les statuts',
    pending: 'En attente',
    validated: 'Validee',
    shipped: 'Expediee',
    delivered: 'Livree',
    cancelled: 'Annulee',
    orderId: 'N° Commande',
    viewDetails: 'Voir details',
    close: 'Fermer',
    save: 'Enregistrer',
    noOrders: 'Aucune commande trouvee',
    noOrdersText: 'Ajustez vos filtres ou attendez de nouvelles commandes.',
    productStatus: 'Statut Produit',
    inStock: 'En stock',
    lowStock: 'Stock faible',
    outOfStock: 'Rupture de stock',
    bulkDelete: 'Supprimer la selection',
    deleteSelected: 'Supprimer la selection',
    bulkPromo: 'Promo sur la selection',
    sold: 'Vendus',
    stock: 'Stock',
    dashboard: 'Dashboard',
    ordersTab: 'Commandes',
    productsTab: 'Produits',
    categoriesTab: 'Categories',
    feedbackTab: 'Feedback',
    contactsTab: 'Contacts',
    feedbackTitle: 'Feedback',
    feedbackSubtitle: 'Partagez votre experience',
    sendFeedback: 'Envoyer le feedback',
    feedbackAdded: 'Feedback ajoute',
    feedbackDeleted: 'Feedback supprime',
    feedbackThankYou: 'Merci pour votre avis.',
    newCategory: 'Nouvelle categorie',
    changeImage: 'Changer l\'image',
    visible: 'Visible',
    hidden: 'Masque',
    categoryAdded: 'Categorie ajoutee',
    categorySaveFailed: 'Echec de l\'enregistrement',
    categorySaveFailedText: 'Impossible d\'enregistrer la categorie.',
    deleteCategoryTitle: 'Supprimer cette categorie ?',
    deleteCategoryMessage: 'sera supprimee de la liste et de Nos Produits.',
    categoryDeleted: 'Categorie supprimee',
    socialMedia: 'Reseaux sociaux',
    selectedProducts: 'produits selectionnes',
    bulkDeleteConfirm: 'Vous allez supprimer',
    productsWord: 'produits',
    bulkPromoMessage: 'produits mis en promo.',
    googleMapsLink: 'Voir sur Google Maps',
    galleryImages: 'Galerie d\'images',
    uploadGallery: 'Ajouter des images',
    maxGalleryImages: 'Maximum 7 images supplementaires',
    removeImage: 'Supprimer l\'image',
    contactMessages: 'Messages de contact',
    unread: 'Non lu',
    markAsRead: 'Marquer comme lu',
    noContacts: 'Aucun message de contact',
    noContactsText: 'Aucun message recu pour le moment.',
    contactDeleted: 'Contact supprime',
    totalMessages: 'Total messages',
    unreadMessages: 'Non lus',
    readMessages: 'Lus',
    productSaveError: 'Erreur d\'enregistrement',
    productSaveErrorText: 'Impossible d\'enregistrer le produit.',
    date: 'Date',
    findUsOnMap: 'Trouvez-nous',
    processingText: 'Traitement en cours...',
    orderSuccessTitle: 'Merci pour votre commande !',
    orderSuccessMessage: 'Votre commande a été reçue avec succès. Nous vous appellerons bientôt pour la confirmation. Merci !',
    confirmDelete: 'Voulez-vous vraiment supprimer',
    selected: 'sélectionné(s)',
  },
  en: {
    home: 'Home',
    shop: 'Shop',
    about: 'About',
    contact: 'Contact',
    admin: 'Admin',
    cameras: 'Cameras',
    accessories: 'Accessories',
    laptop: 'Laptop',
    searchPlaceholder: 'Search...',
    noSearchResults: 'No results',
    viewAllResults: 'View all results',
    heroTitle: 'The Phone House  - Phones and Accessories',
    heroText:
      'Discover high-end professional gear to capture every important moment.',
    buy: 'Shop now',
    moreInfo: 'More information',
    ourProducts: 'Our Products',
    featured: 'Featured Products',
    promotions: 'Promotions',
    new: 'New',
    add: 'Add',
    addToCart: 'Add to cart',
    addedToCart: 'Product added to cart',
    addedToWishlist: 'Added to wishlist',
    removedFromWishlist: 'Removed from wishlist',
    catalog: 'Catalog',
    catalogTitle: 'Premium photo gear',
    productCount: 'product(s)',
    searchProduct: 'Search a product...',
    allCategories: 'All categories',
    allBrands: 'All brands',
    sortBy: 'Sort by',
    priceLowHigh: 'Price: low to high',
    priceHighLow: 'Price: high to low',
    noProducts: 'No products found',
    noProductsText: 'Try another search or change the filters.',
    relatedProducts: 'Related products',
    productNotFound: 'Product not found',
    backToCatalog: 'Back to catalog',
    cart: 'Cart',
    cartEmpty: 'Your cart is empty',
    cartEmptyText: 'Add your favorite cameras, laptops and accessories.',
    viewCatalog: 'View catalog',
    checkoutTitle: 'Complete order',
    clearCart: 'Clear cart',
    summary: 'Summary',
    subtotal: 'Subtotal',
    delivery: 'Delivery',
    toConfirm: 'To confirm',
    total: 'Total',
    requestOrder: 'Request order',
    confirmClearTitle: 'Clear cart?',
    confirmClearMessage: 'All products will be removed from your cart.',
    confirmOrderTitle: 'Confirm order?',
    confirmOrderMessage: 'Do you want to confirm this order?',
    orderCreated: 'Order created',
    orderCreatedMessage: 'Your order has been recorded successfully.',
    confirmRemoveTitle: 'Remove this product?',
    remove: 'Remove',
    cancel: 'Cancel',
    clearedCart: 'Cart cleared',
    removedProduct: 'Product removed',
    wishlist: 'Wishlist',
    wishlistEmpty: 'No favorites yet',
    wishlistEmptyText: 'Keep your favorite products here for quick access.',
    exploreProducts: 'Explore products',
    wishlistTitle: 'Your selection',
    aboutTitle: 'A store for demanding creators',
    selectionPremium: 'Premium selection',
    selectionText:
      'The Phone House  highlights phones, accessories and laptops chosen for photo and video creation.',
    localBase: 'Based in Algeria',
    localText:
      'The team supports customers from Bordj Bou Arreridj with a simple, direct and local approach.',
    usefulAdvice: 'Useful advice',
    usefulAdviceText:
      'Need to choose between two models? Support helps you find the right gear.',
    contactTitle: 'Tell us what you need',
    address: 'Address',
    addressText: 'Bordj Bou Arreridj, Algeria. Delivery depends on the order.',
    support: 'Support',
    supportText: '7-day support for products, availability and orders.',
    quickRequest: 'Quick request',
    name: 'Name',
    phoneOrEmail: 'Phone or email',
    message: 'Your message',
    send: 'Send',
    messagePrepared: 'Message delivered',
    messagePreparedText: 'Your message has been delivered successfully, we will process it as soon as possible, thank you.',
    pageNotFound: 'Page not found',
    pageNotFoundText: 'This page does not exist or was moved.',
    backHome: 'Back home',
    footerText:
      'Your destination for the best photo gear, laptops and creation accessories.',
    navigation: 'Navigation',
    quickLinks: 'Quick links',
    products: 'Products',
    rights: '2026 The Phone house. All rights reserved.',
    deliveryTitle: 'Delivery',
    deliveryText: 'Fast delivery across Algeria',
    location: 'Location',
    supportClient: 'Customer support',
    securePayment: 'Secure payment',
    securePaymentText: 'Reliable transactions and order tracking',
    adminTitle: 'Admin dashboard',
    adminSubtitle: 'Manage products, promotions and store statistics.',
    adminLogin: 'Admin login',
    adminLoginText: 'Restricted access for store management.',
    username: 'Username',
    password: 'Password',
    login: 'Login',
    logout: 'Logout',
    invalidCredentials: 'Invalid credentials',
    signedIn: 'Signed in',
    backToStore: 'View store',
    adminEssential: 'Back office',
    charts: 'Visual statistics',
    categoryDistribution: 'Products by category',
    promotionShare: 'Promotion status',
    uploadImage: 'Upload image',
    uploadSecondImage: 'Upload image 2',
    activePromos: 'Active promos',
    normalProducts: 'Standard products',
    totalProducts: 'Products',
    promoProducts: 'Promotions',
    categoriesStat: 'Categories',
    inventoryValue: 'Catalog value',
    productManager: 'Product manager',
    addProduct: 'Add product',
    updateProduct: 'Update product',
    resetForm: 'Reset',
    brand: 'Brand',
    category: 'Category',
    price: 'Price',
    rating: 'Rating',
    image: 'Image',
    secondImage: 'Image 2',
    description: 'Description',
    isNew: 'New',
    isPromo: 'Promotion',
    discount: 'Discount %',
    actions: 'Actions',
    edit: 'Edit',
    promo: 'Promo',
    productSaved: 'Product saved',
    productDeleted: 'Product deleted',
    confirmDeleteProduct: 'Delete this product?',
    confirmDeleteProductText: 'It will disappear from the public catalog.',
    promotionUpdated: 'Promotion updated',
    shareExperience: 'Share your experience',
    personalInfo: 'Personal Information',
    firstName: 'First Name',
    lastName: 'Last Name',
    phone: 'Phone',
    emailOptional: 'Email (optional)',
    shippingAddress: 'Shipping Address',
    wilaya: 'Wilaya',
    selectWilaya: 'Select a wilaya',
    baladiya: 'Commune (Baladiya)',
    selectBaladiya: 'Select a commune',
    fullAddress: 'Full Address',
    postalCode: 'Postal Code (optional)',
    orderDetails: 'Order Details',
    quantity: 'Quantity',
    additionalNotes: 'Additional Notes',
    placeOrder: 'Place Order',
    fieldRequired: 'This field is required',
    invalidPhone: 'Invalid phone number',
    invalidEmail: 'Invalid email address',
    orders: 'Orders',
    totalOrders: 'Total Orders',
    totalRevenue: 'Total Revenue',
    averageOrderValue: 'Average Order Value',
    pendingOrders: 'Pending Orders',
    ordersByWilaya: 'Orders by Wilaya',
    ordersByProduct: 'Orders by Product',
    monthlySales: 'Monthly Sales',
    orderStatusDistribution: 'Order Status Distribution',
    topSellingProducts: 'Top Selling Products',
    revenueByDay: 'Revenue by Day',
    searchOrders: 'Search orders...',
    status: 'Status',
    orderDate: 'Date',
    customer: 'Customer',
    allStatuses: 'All statuses',
    pending: 'Pending',
    validated: 'Validated',
    shipped: 'Shipped',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    orderId: 'Order ID',
    viewDetails: 'View details',
    close: 'Close',
    save: 'Save',
    noOrders: 'No orders found',
    noOrdersText: 'Adjust your filters or wait for new orders.',
    productStatus: 'Product Status',
    inStock: 'In stock',
    lowStock: 'Low stock',
    outOfStock: 'Out of stock',
    bulkDelete: 'Delete selection',
    deleteSelected: 'Delete selected',
    bulkPromo: 'Promo selection',
    sold: 'Sold',
    stock: 'Stock',
    dashboard: 'Dashboard',
    ordersTab: 'Orders',
    productsTab: 'Products',
    categoriesTab: 'Categories',
    feedbackTab: 'Feedback',
    contactsTab: 'Contacts',
    feedbackTitle: 'Feedback',
    feedbackSubtitle: 'Share your experience',
    sendFeedback: 'Send feedback',
    feedbackAdded: 'Feedback added',
    feedbackDeleted: 'Feedback deleted',
    feedbackThankYou: 'Thank you for sharing your opinion.',
    newCategory: 'New category',
    changeImage: 'Change image',
    visible: 'Visible',
    hidden: 'Hidden',
    categoryAdded: 'Category added',
    categorySaveFailed: 'Category save failed',
    categorySaveFailedText: 'Unable to save category to the backend.',
    deleteCategoryTitle: 'Delete this category?',
    deleteCategoryMessage: 'will be removed from the category list and from Our Products.',
    categoryDeleted: 'Category deleted',
    socialMedia: 'Social media',
    selectedProducts: 'products selected',
    bulkDeleteConfirm: 'You are about to delete',
    productsWord: 'products',
    bulkPromoMessage: 'products set to promo.',
    googleMapsLink: 'View on Google Maps',
    galleryImages: 'Image gallery',
    uploadGallery: 'Add images',
    maxGalleryImages: 'Maximum 7 additional images',
    removeImage: 'Remove image',
    contactMessages: 'Contact messages',
    unread: 'Unread',
    markAsRead: 'Mark as read',
    noContacts: 'No contact messages',
    noContactsText: 'No messages received yet.',
    contactDeleted: 'Contact deleted',
    totalMessages: 'Total messages',
    unreadMessages: 'Unread',
    readMessages: 'Read',
    productSaveError: 'Save error',
    productSaveErrorText: 'Unable to save product to the backend.',
    date: 'Date',
    findUsOnMap: 'Find us',
    processingText: 'Processing...',
    orderSuccessTitle: 'Thank you for your order!',
    orderSuccessMessage: 'Your order has been received successfully. We will call you shortly for confirmation. Thank you!',
    confirmDelete: 'Are you sure you want to delete',
    selected: 'selected',
  },
  ar: {
    home: 'الرئيسية',
    shop: 'المتجر',
    about: 'من نحن',
    contact: 'اتصل بنا',
    admin: 'الإدارة',
    cameras: 'كاميرات',
    accessories: 'إكسسوارات',
    laptop: 'حاسوب',
    searchPlaceholder: 'ابحث...',
    noSearchResults: 'لا توجد نتائج',
    viewAllResults: 'عرض كل النتائج',
    heroTitle: 'The Phone House - الهواتف والإكسسوارات',
    heroText: 'اكتشف معدات احترافية عالية الجودة لالتقاط كل لحظة مهمة.',
    buy: 'تسوق الآن',
    moreInfo: 'معلومات أكثر',
    ourProducts: 'منتجاتنا',
    featured: 'منتجات مميزة',
    promotions: 'العروض',
    new: 'جديد',
    add: 'إضافة',
    addToCart: 'إضافة للسلة',
    addedToCart: 'تمت إضافة المنتج للسلة',
    addedToWishlist: 'تمت الإضافة للمفضلة',
    removedFromWishlist: 'تم الحذف من المفضلة',
    catalog: 'الكتالوج',
    catalogTitle: 'معدات تصوير احترافية',
    productCount: 'منتج',
    searchProduct: 'ابحث عن منتج...',
    allCategories: 'كل التصنيفات',
    allBrands: 'كل العلامات',
    sortBy: 'ترتيب حسب',
    priceLowHigh: 'السعر: من الأقل للأعلى',
    priceHighLow: 'السعر: من الأعلى للأقل',
    noProducts: 'لم يتم العثور على منتجات',
    noProductsText: 'جرب بحثا آخر أو غير الفلاتر.',
    relatedProducts: 'منتجات مشابهة',
    productNotFound: 'المنتج غير موجود',
    backToCatalog: 'العودة للكتالوج',
    cart: 'السلة',
    cartEmpty: 'سلتك فارغة',
    cartEmptyText: 'أضف الكاميرات والحواسيب والإكسسوارات المفضلة لديك.',
    viewCatalog: 'عرض الكتالوج',
    checkoutTitle: 'إتمام الطلب',
    clearCart: 'تفريغ السلة',
    summary: 'الملخص',
    subtotal: 'المجموع الفرعي',
    delivery: 'التوصيل',
    toConfirm: 'للتأكيد',
    total: 'الإجمالي',
    requestOrder: 'طلب الشراء',
    confirmClearTitle: 'تفريغ السلة؟',
    confirmClearMessage: 'سيتم حذف كل المنتجات من السلة.',
    confirmOrderTitle: 'تأكيد الطلب؟',
    confirmOrderMessage: 'هل تريد تأكيد هذا الطلب؟',
    orderCreated: 'تم إنشاء الطلب',
    orderCreatedMessage: 'تم تسجيل طلبك بنجاح.',
    confirmRemoveTitle: 'حذف هذا المنتج؟',
    remove: 'حذف',
    cancel: 'إلغاء',
    clearedCart: 'تم تفريغ السلة',
    removedProduct: 'تم حذف المنتج',
    wishlist: 'المفضلة',
    wishlistEmpty: 'لا توجد منتجات مفضلة بعد',
    wishlistEmptyText: 'احتفظ بمنتجاتك المفضلة هنا للوصول إليها بسرعة.',
    exploreProducts: 'استكشف المنتجات',
    wishlistTitle: 'اختياراتك',
    aboutTitle: 'متجر لصناع المحتوى المحترفين',
    selectionPremium: 'اختيار ممتاز',
    selectionText:
      'The Phone House يسلط الضوء على الهواتف والإكسسوارات والحواسيب المختارة لإنشاء الصور والفيديو.',
    localBase: 'مقرنا في الجزائر',
    localText: 'نرافق العملاء من برج بوعريريج بطريقة بسيطة ومحلية.',
    usefulAdvice: 'نصيحة مفيدة',
    usefulAdviceText:
      'تحتاج للاختيار بين موديلين؟ الدعم يساعدك على إيجاد المعدات المناسبة.',
    contactTitle: 'أخبرنا بما تحتاجه',
    address: 'العنوان',
    addressText: 'برج بوعريريج، الجزائر. التوصيل حسب الطلب.',
    support: 'الدعم',
    supportText: 'دعم طوال الأسبوع للمنتجات والتوفر والطلبات.',
    quickRequest: 'طلب سريع',
    name: 'الاسم',
    phoneOrEmail: 'الهاتف أو البريد',
    message: 'رسالتك',
    send: 'إرسال',
    messagePrepared: 'تم تسليم الرسالة',
    messagePreparedText: 'تم تسليم رسالتك بنجاح، سنقوم بمعالجتها في أقرب وقت ممكن، شكرا.',
    pageNotFound: 'الصفحة غير موجودة',
    pageNotFoundText: 'هذه الصفحة غير موجودة أو تم نقلها.',
    backHome: 'العودة للرئيسية',
    footerText: 'وجهتك لأفضل معدات التصوير والحواسيب وإكسسوارات الإبداع.',
    navigation: 'التنقل',
    quickLinks: 'روابط سريعة',
    products: 'المنتجات',
    rights: '2026 The Phone house. كل الحقوق محفوظة.',
    deliveryTitle: 'التوصيل',
    deliveryText: 'توصيل سريع في كل الجزائر',
    location: 'الموقع',
    supportClient: 'دعم العملاء',
    securePayment: 'دفع آمن',
    securePaymentText: 'معاملات موثوقة وتتبع الطلب',
    adminTitle: 'لوحة الإدارة',
    adminSubtitle: 'إدارة المنتجات والعروض وإحصائيات المتجر.',
    adminLogin: 'دخول الإدارة',
    adminLoginText: 'وصول مخصص لإدارة المتجر.',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    login: 'دخول',
    logout: 'خروج',
    invalidCredentials: 'بيانات الدخول غير صحيحة',
    signedIn: 'تم تسجيل الدخول',
    backToStore: 'عرض المتجر',
    adminEssential: 'لوحة التحكم',
    charts: 'إحصائيات مرئية',
    categoryDistribution: 'المنتجات حسب التصنيف',
    promotionShare: 'حالة العروض',
    uploadImage: 'رفع صورة',
    uploadSecondImage: 'رفع صورة 2',
    activePromos: 'عروض نشطة',
    normalProducts: 'منتجات عادية',
    totalProducts: 'المنتجات',
    promoProducts: 'العروض',
    categoriesStat: 'التصنيفات',
    inventoryValue: 'قيمة الكتالوج',
    productManager: 'إدارة المنتجات',
    addProduct: 'إضافة منتج',
    updateProduct: 'تحديث المنتج',
    resetForm: 'إعادة ضبط',
    brand: 'العلامة',
    category: 'التصنيف',
    price: 'السعر',
    rating: 'التقييم',
    image: 'الصورة',
    secondImage: 'الصورة 2',
    description: 'الوصف',
    isNew: 'جديد',
    isPromo: 'عرض',
    discount: 'التخفيض %',
    actions: 'إجراءات',
    edit: 'تعديل',
    promo: 'عرض',
    productSaved: 'تم حفظ المنتج',
    productDeleted: 'تم حذف المنتج',
    confirmDeleteProduct: 'حذف هذا المنتج؟',
    confirmDeleteProductText: 'سيختفي من الكتالوج العام.',
    promotionUpdated: 'تم تحديث العرض',
    shareExperience: 'شارك تجربتك',
    personalInfo: 'المعلومات الشخصية',
    firstName: 'الاسم الأول',
    lastName: 'اللقب',
    phone: 'رقم الهاتف',
    emailOptional: 'البريد الإلكتروني (اختياري)',
    shippingAddress: 'عنوان التوصيل',
    wilaya: 'الولاية',
    selectWilaya: 'اختر الولاية',
    baladiya: 'البلدية',
    selectBaladiya: 'اختر البلدية',
    fullAddress: 'العنوان الكامل',
    postalCode: 'الرمز البريدي (اختياري)',
    orderDetails: 'تفاصيل الطلب',
    quantity: 'الكمية',
    additionalNotes: 'ملاحظات إضافية',
    placeOrder: 'تأكيد الطلب',
    fieldRequired: 'هذا الحقل مطلوب',
    invalidPhone: 'رقم هاتف غير صالح',
    invalidEmail: 'بريد إلكتروني غير صالح',
    orders: 'الطلبات',
    totalOrders: 'إجمالي الطلبات',
    totalRevenue: 'إجمالي الدخل',
    averageOrderValue: 'متوسط قيمة الطلب',
    pendingOrders: 'طلبات قيد الانتظار',
    ordersByWilaya: 'الطلبات حسب الولاية',
    ordersByProduct: 'الطلبات حسب المنتج',
    monthlySales: 'المبيعات الشهرية',
    orderStatusDistribution: 'توزيع حالات الطلبات',
    topSellingProducts: 'المنتجات الأكثر مبيعاً',
    revenueByDay: 'الدخل اليومي',
    searchOrders: 'البحث في الطلبات...',
    status: 'الحالة',
    orderDate: 'التاريخ',
    customer: 'الزبون',
    allStatuses: 'كل الحالات',
    pending: 'قيد الانتظار',
    validated: 'مؤكد',
    shipped: 'تم الشحن',
    delivered: 'تم التوصيل',
    cancelled: 'ملغى',
    orderId: 'رقم الطلب',
    viewDetails: 'عرض التفاصيل',
    close: 'إغلاق',
    save: 'حفظ',
    noOrders: 'لم يتم العثور على طلبات',
    noOrdersText: 'قم بتغيير الفلاتر أو انتظر طلبات جديدة.',
    productStatus: 'حالة المنتج',
    inStock: 'متوفر',
    lowStock: 'كمية قليلة',
    outOfStock: 'نفد من المخزون',
    bulkDelete: 'حذف المحدد',
    deleteSelected: 'حذف المحدد',
    bulkPromo: 'تخفيض المحدد',
    sold: 'المبيعات',
    stock: 'المخزون',
    dashboard: 'لوحة المعلومات',
    ordersTab: 'الطلبات',
    productsTab: 'المنتجات',
    categoriesTab: 'التصنيفات',
    feedbackTab: 'التقييمات',
    contactsTab: 'الرسائل',
    feedbackTitle: 'التقييمات',
    feedbackSubtitle: 'شارك تجربتك',
    sendFeedback: 'إرسال التقييم',
    feedbackAdded: 'تم إضافة التقييم',
    feedbackDeleted: 'تم حذف التقييم',
    feedbackThankYou: 'شكراً لمشاركة رأيك.',
    newCategory: 'تصنيف جديد',
    changeImage: 'تغيير الصورة',
    visible: 'مرئي',
    hidden: 'مخفي',
    categoryAdded: 'تم إضافة التصنيف',
    categorySaveFailed: 'فشل حفظ التصنيف',
    categorySaveFailedText: 'تعذر حفظ التصنيف.',
    deleteCategoryTitle: 'حذف هذا التصنيف؟',
    deleteCategoryMessage: 'سيتم حذفه من القائمة ومن منتجاتنا.',
    categoryDeleted: 'تم حذف التصنيف',
    socialMedia: 'شبكات التواصل',
    selectedProducts: 'منتج محدد',
    bulkDeleteConfirm: 'سيتم حذف',
    productsWord: 'منتج',
    bulkPromoMessage: 'منتج تم وضعه في عرض.',
    googleMapsLink: 'عرض على خرائط جوجل',
    galleryImages: 'معرض الصور',
    uploadGallery: 'إضافة صور',
    maxGalleryImages: '7 صور إضافية كحد أقصى',
    removeImage: 'حذف الصورة',
    contactMessages: 'رسائل الاتصال',
    unread: 'غير مقروء',
    markAsRead: 'تعليم كمقروء',
    noContacts: 'لا توجد رسائل اتصال',
    noContactsText: 'لم يتم استلام أي رسائل بعد.',
    contactDeleted: 'تم حذف الرسالة',
    totalMessages: 'إجمالي الرسائل',
    unreadMessages: 'غير مقروءة',
    readMessages: 'مقروءة',
    productSaveError: 'خطأ في الحفظ',
    productSaveErrorText: 'تعذر حفظ المنتج.',
    date: 'التاريخ',
    findUsOnMap: 'موقعنا',
    processingText: 'جاري المعالجة...',
    orderSuccessTitle: 'شكراً لطلبك!',
    orderSuccessMessage: 'تم استلام طلبك بنجاح. سنتصل بك قريباً لتأكيد الطلب. شكراً لك!',
    confirmDelete: 'هل أنت متأكد من حذف',
    selected: 'محدد',
  },
};

const languages = [
  { code: 'fr', label: 'FR' },
  { code: 'en', label: 'EN' },
  { code: 'ar', label: 'AR' },
];

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => window.localStorage.getItem('ab-store-language') || 'fr'
  );

  useEffect(() => {
    window.localStorage.setItem('ab-store-language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const value = useMemo(
    () => ({
      dir: language === 'ar' ? 'rtl' : 'ltr',
      language,
      languages,
      setLanguage,
      t: (key) => dictionaries[language][key] || dictionaries.fr[key] || key,
    }),
    [language]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}
