import { useEffect, useMemo, useState } from 'react';
import { LanguageContext } from './language';

const dictionaries = {
  fr: {
    home: 'Accueil',
    shop: 'Shop',
    about: 'A propos',
    contact: 'Contact',
    admin: 'Admin',
    phones: 'Telephones',
    accessories: 'Accessoires',
    laptop: 'Ordinateurs',
    searchPlaceholder: 'Rechercher un telephone, accessoire...',
    noSearchResults: 'Aucun resultat',
    viewAllResults: 'Voir tous les resultats',
    heroTitle: 'The Phone - Telephones et Accessoires',
    heroText:
      'Telephones originaux, accessoires premium et service de confiance a El Eulma.',
    buy: 'Acheter',
    moreInfo: "Plus d'informations",
    ourProducts: 'Nos Produits',
    featured: 'Produits a la une',
    promotions: 'Promotions',
    new: 'Nouveau',
    add: 'Ajouter',
    addToCart: 'Ajouter au panier',
    addedToCart: 'Produit ajoute au panier',
    addedToWishlist: 'Ajoute aux favoris',
    removedFromWishlist: 'Retire des favoris',
    catalog: 'Catalogue',
    catalogTitle: 'Telephones et accessoires premium',
    productCount: 'produit(s)',
    searchProduct: 'Rechercher un produit...',
    allCategories: 'Toutes les categories',
    allBrands: 'Toutes les marques',
    sortBy: 'Trier par',
    priceLowHigh: 'Prix: bas vers haut',
    priceHighLow: 'Prix: haut vers bas',
    noProducts: 'Aucun produit trouve',
    noProductsText: 'Essayez une autre recherche ou changez les filtres.',
    relatedProducts: 'Produits similaires',
    productNotFound: 'Produit introuvable',
    backToCatalog: 'Retour au catalogue',
    cart: 'Panier',
    cartEmpty: 'Votre panier est vide',
    cartEmptyText: 'Ajoutez vos telephones et accessoires favoris.',
    viewCatalog: 'Voir le catalogue',
    checkoutTitle: 'Finaliser la commande',
    clearCart: 'Vider le panier',
    summary: 'Resume',
    subtotal: 'Sous-total',
    delivery: 'Livraison',
    toConfirm: 'A confirmer',
    total: 'Total',
    requestOrder: 'Demander la commande',
    confirmClearTitle: 'Vider le panier ?',
    confirmClearMessage: 'Tous les produits seront retires de votre panier.',
    confirmOrderTitle: 'Confirmer la commande ?',
    confirmOrderMessage: 'Voulez-vous valider cette commande ?',
    orderCreated: 'Commande creee',
    orderCreatedMessage: 'Votre commande a ete enregistree avec succes.',
    confirmRemoveTitle: 'Supprimer ce produit ?',
    remove: 'Supprimer',
    cancel: 'Annuler',
    clearedCart: 'Panier vide',
    removedProduct: 'Produit retire',
    wishlist: 'Favoris',
    wishlistEmpty: 'Aucun favori pour le moment',
    wishlistEmptyText:
      'Gardez vos produits preferes ici pour les retrouver rapidement.',
    exploreProducts: 'Explorer les produits',
    wishlistTitle: 'Votre selection',
    aboutTitle: 'Votre boutique mobile de confiance',
    selectionPremium: 'Selection premium',
    selectionText:
      'The Phone propose des telephones, accessoires et gadgets choisis pour un usage quotidien exigeant.',
    localBase: 'Base a El Eulma',
    localText:
      "Notre equipe vous accompagne depuis El Eulma avec un service simple, direct et local.",
    usefulAdvice: 'Conseil personnalise',
    usefulAdviceText:
      'Besoin d aide pour choisir un modele ou une configuration ? Notre equipe vous guide selon votre budget et vos besoins.',
    contactTitle: 'Parlez-nous de votre besoin',
    address: 'Adresse',
    addressText:
      'El Eulma, Algerie. Livraison disponible selon la commande.',
    support: 'Support',
    supportText:
      'Assistance 7j/7 pour les demandes produit, disponibilites et commandes.',
    quickRequest: 'Demande rapide',
    name: 'Nom',
    phoneOrEmail: 'Telephone ou email',
    message: 'Votre message',
    send: 'Envoyer',
    messagePrepared: 'Message envoye',
    messagePreparedText: 'Votre message a ete livre avec succes. Nous le traiterons des que possible. Merci.',
    pageNotFound: 'Page introuvable',
    pageNotFoundText: "Cette page n'existe pas ou a ete deplacee.",
    backHome: "Retour a l'accueil",
    footerText:
      'Votre destination pour les meilleurs telephones, accessoires et gadgets a El Eulma.',
    navigation: 'Navigation',
    quickLinks: 'Liens rapides',
    products: 'Produits',
    rights: '2026 The Phone. Tous droits reserves.',
    deliveryTitle: 'Livraison',
    deliveryText: 'Livraison rapide partout en Algerie',
    location: 'Localisation',
    supportClient: 'Support client',
    securePayment: 'Paiement securise',
    securePaymentText: 'Transactions fiables et suivi de commande',
    adminTitle: 'Dashboard admin',
    adminSubtitle: 'Gerez les produits, promotions et statistiques du store.',
    adminLogin: 'Connexion admin',
    adminLoginText: 'Acces reserve a la gestion du store.',
    username: 'Utilisateur',
    password: 'Mot de passe',
    login: 'Connexion',
    logout: 'Deconnexion',
    invalidCredentials: 'Identifiants incorrects',
    signedIn: 'Connexion reussie',
    backToStore: 'Voir le store',
    adminEssential: 'Back office',
    charts: 'Statistiques visuelles',
    categoryDistribution: 'Produits par categorie',
    promotionShare: 'Etat des promotions',
    uploadImage: 'Uploader image',
    uploadSecondImage: 'Uploader image 2',
    activePromos: 'Promos actives',
    normalProducts: 'Produits standards',
    totalProducts: 'Produits',
    promoProducts: 'Promotions',
    categoriesStat: 'Categories',
    inventoryValue: 'Valeur catalogue',
    productManager: 'Gestion des produits',
    addProduct: 'Ajouter un produit',
    updateProduct: 'Mettre a jour',
    resetForm: 'Reinitialiser',
    brand: 'Marque',
    category: 'Categorie',
    price: 'Prix',
    rating: 'Note',
    image: 'Image',
    secondImage: 'Image 2',
    description: 'Description',
    isNew: 'Nouveau',
    isPromo: 'Promotion',
    discount: 'Reduction %',
    actions: 'Actions',
    edit: 'Modifier',
    promo: 'Promo',
    productSaved: 'Produit enregistre',
    productDeleted: 'Produit supprime',
    confirmDeleteProduct: 'Supprimer ce produit ?',
    confirmDeleteProductText: 'Il disparaitra du catalogue public.',
    promotionUpdated: 'Promotion mise a jour',
    shareExperience: 'Partagez votre experience',
    personalInfo: 'Informations personnelles',
    firstName: 'Prenom',
    lastName: 'Nom de famille',
    phone: 'Telephone',
    emailOptional: 'Email (optionnel)',
    shippingAddress: 'Adresse de livraison',
    wilaya: 'Wilaya',
    selectWilaya: 'Selectionner une wilaya',
    baladiya: 'Commune (Baladiya)',
    selectBaladiya: 'Selectionner une commune',
    fullAddress: 'Adresse complete',
    postalCode: 'Code postal (optionnel)',
    orderDetails: 'Details de la commande',
    quantity: 'Quantite',
    additionalNotes: 'Notes additionnelles',
    placeOrder: 'Passer la commande',
    fieldRequired: 'Ce champ est requis',
    invalidPhone: 'Numero de telephone invalide',
    invalidEmail: 'Adresse email invalide',
    orders: 'Commandes',
    totalOrders: 'Total Commandes',
    totalRevenue: 'Revenu Total',
    averageOrderValue: 'Panier Moyen',
    pendingOrders: 'Commandes en attente',
    ordersByWilaya: 'Commandes par Wilaya',
    ordersByProduct: 'Commandes par Produit',
    monthlySales: 'Ventes Mensuelles',
    orderStatusDistribution: 'Statuts des Commandes',
    topSellingProducts: 'Meilleures Ventes',
    revenueByDay: 'Revenu par Jour',
    searchOrders: 'Rechercher une commande...',
    status: 'Statut',
    orderDate: 'Date',
    customer: 'Client',
    allStatuses: 'Tous les statuts',
    pending: 'En attente',
    validated: 'Validee',
    shipped: 'Expediee',
    delivered: 'Livree',
    cancelled: 'Annulee',
    orderId: 'N° Commande',
    viewDetails: 'Voir details',
    close: 'Fermer',
    save: 'Enregistrer',
    noOrders: 'Aucune commande trouvee',
    noOrdersText: 'Ajustez vos filtres ou attendez de nouvelles commandes.',
    productStatus: 'Statut Produit',
    inStock: 'En stock',
    lowStock: 'Stock faible',
    outOfStock: 'Rupture de stock',
    bulkDelete: 'Supprimer la selection',
    deleteSelected: 'Supprimer la selection',
    bulkPromo: 'Promo sur la selection',
    sold: 'Vendus',
    stock: 'Stock',
    dashboard: 'Dashboard',
    ordersTab: 'Commandes',
    productsTab: 'Produits',
    categoriesTab: 'Categories',
    feedbackTab: 'Feedback',
    contactsTab: 'Contacts',
    feedbackTitle: 'Feedback',
    feedbackSubtitle: 'Partagez votre experience',
    sendFeedback: 'Envoyer le feedback',
    feedbackAdded: 'Feedback ajoute',
    feedbackDeleted: 'Feedback supprime',
    feedbackThankYou: 'Merci pour votre avis.',
    newCategory: 'Nouvelle categorie',
    changeImage: 'Changer l\'image',
    visible: 'Visible',
    hidden: 'Masque',
    categoryAdded: 'Categorie ajoutee',
    categorySaveFailed: 'Echec de l\'enregistrement',
    categorySaveFailedText: 'Impossible d\'enregistrer la categorie.',
    deleteCategoryTitle: 'Supprimer cette categorie ?',
    deleteCategoryMessage: 'sera supprimee de la liste et de Nos Produits.',
    categoryDeleted: 'Categorie supprimee',
    socialMedia: 'Reseaux sociaux',
    selectedProducts: 'produits selectionnes',
    bulkDeleteConfirm: 'Vous allez supprimer',
    productsWord: 'produits',
    bulkPromoMessage: 'produits mis en promo.',
    googleMapsLink: 'Voir sur Google Maps',
    galleryImages: 'Galerie d\'images',
    uploadGallery: 'Ajouter des images',
    maxGalleryImages: 'Maximum 7 images supplementaires',
    removeImage: 'Supprimer l\'image',
    contactMessages: 'Messages de contact',
    unread: 'Non lu',
    markAsRead: 'Marquer comme lu',
    noContacts: 'Aucun message de contact',
    noContactsText: 'Aucun message recu pour le moment.',
    contactDeleted: 'Contact supprime',
    totalMessages: 'Total messages',
    unreadMessages: 'Non lus',
    readMessages: 'Lus',
    productSaveError: 'Erreur d\'enregistrement',
    productSaveErrorText: 'Impossible d\'enregistrer le produit.',
    date: 'Date',
    findUsOnMap: 'Trouvez-nous',
    processingText: 'Traitement en cours...',
    orderSuccessTitle: 'Merci pour votre commande !',
    orderSuccessMessage: 'Votre commande a été reçue avec succès. Nous vous appellerons bientôt pour la confirmation. Merci !',
    confirmDelete: 'Voulez-vous vraiment supprimer',
    selected: 'sélectionné(s)',
    whatsappUs: 'WhatsApp',
    callUs: 'Appeler',
    noCategoriesYet: 'Aucune categorie pour le moment',
    color: 'Couleur',
    storage: 'Stockage',
    colorPlaceholder: 'Ex: Noir, Blanc, Or',
    storagePlaceholder: 'Ex: 128GB, 256GB, 512GB',
    swipeCategories: 'Faites defiler pour voir plus de categories',
    scrollCategoriesDesktop: 'Utilisez les fleches pour voir 3 categories a la fois',
    scrollLeft: 'Defiler vers la gauche',
    scrollRight: 'Defiler vers la droite',
    colorOptionsHint: 'Choisissez rapidement ou ajoutez une valeur personnalisee',
    storageOptionsHint: 'Choisissez rapidement ou ajoutez une capacite personnalisee',
    quickChoose: 'Choix rapide',
    addCustomValue: 'Ajouter',
    chooseOptions: 'Choisir les options',
    selectOptionsInCart: 'Veuillez choisir toutes les options pour chaque produit',
    productOptions: 'Options produit',
    addOptionGroup: 'Ajouter une option',
    optionNamePlaceholder: 'Ex: Couleur, Stockage, RAM',
    optionValuesPlaceholder: 'Valeurs separees par des virgules',
    selectAllOptions: 'Selectionnez toutes les options',
    selectedOptions: 'Options choisies',
    removeOptionGroup: 'Supprimer',
    customOptionValues: 'Valeurs de l\'option',
    decreaseQuantity: 'Diminuer la quantite',
    increaseQuantity: 'Augmenter la quantite',
  },
  en: {
    home: 'Home',
    shop: 'Shop',
    about: 'About',
    contact: 'Contact',
    admin: 'Admin',
    phones: 'Phones',
    accessories: 'Accessories',
    laptop: 'Laptops',
    searchPlaceholder: 'Search phones, accessories...',
    noSearchResults: 'No results',
    viewAllResults: 'View all results',
    heroTitle: 'The Phone - Phones and Accessories',
    heroText:
      'Original phones, premium accessories and trusted service in El Eulma.',
    buy: 'Shop now',
    moreInfo: 'More information',
    ourProducts: 'Our Products',
    featured: 'Featured Products',
    promotions: 'Promotions',
    new: 'New',
    add: 'Add',
    addToCart: 'Add to cart',
    addedToCart: 'Product added to cart',
    addedToWishlist: 'Added to wishlist',
    removedFromWishlist: 'Removed from wishlist',
    catalog: 'Catalog',
    catalogTitle: 'Premium phones and accessories',
    productCount: 'product(s)',
    searchProduct: 'Search a product...',
    allCategories: 'All categories',
    allBrands: 'All brands',
    sortBy: 'Sort by',
    priceLowHigh: 'Price: low to high',
    priceHighLow: 'Price: high to low',
    noProducts: 'No products found',
    noProductsText: 'Try another search or change the filters.',
    relatedProducts: 'Related products',
    productNotFound: 'Product not found',
    backToCatalog: 'Back to catalog',
    cart: 'Cart',
    cartEmpty: 'Your cart is empty',
    cartEmptyText: 'Add your favorite phones and accessories.',
    viewCatalog: 'View catalog',
    checkoutTitle: 'Complete order',
    clearCart: 'Clear cart',
    summary: 'Summary',
    subtotal: 'Subtotal',
    delivery: 'Delivery',
    toConfirm: 'To confirm',
    total: 'Total',
    requestOrder: 'Request order',
    confirmClearTitle: 'Clear cart?',
    confirmClearMessage: 'All products will be removed from your cart.',
    confirmOrderTitle: 'Confirm order?',
    confirmOrderMessage: 'Do you want to confirm this order?',
    orderCreated: 'Order created',
    orderCreatedMessage: 'Your order has been recorded successfully.',
    confirmRemoveTitle: 'Remove this product?',
    remove: 'Remove',
    cancel: 'Cancel',
    clearedCart: 'Cart cleared',
    removedProduct: 'Product removed',
    wishlist: 'Wishlist',
    wishlistEmpty: 'No favorites yet',
    wishlistEmptyText: 'Keep your favorite products here for quick access.',
    exploreProducts: 'Explore products',
    wishlistTitle: 'Your selection',
    aboutTitle: 'Your trusted mobile store',
    selectionPremium: 'Premium selection',
    selectionText:
      'The Phone offers phones, accessories and gadgets selected for everyday quality and reliability.',
    localBase: 'Based in El Eulma',
    localText:
      'Our team supports customers from El Eulma with a simple, direct and local approach.',
    usefulAdvice: 'Personal advice',
    usefulAdviceText:
      'Need help choosing a model or configuration? Our team guides you based on your budget and needs.',
    contactTitle: 'Tell us what you need',
    address: 'Address',
    addressText: 'El Eulma, Algeria. Delivery depends on the order.',
    support: 'Support',
    supportText: '7-day support for products, availability and orders.',
    quickRequest: 'Quick request',
    name: 'Name',
    phoneOrEmail: 'Phone or email',
    message: 'Your message',
    send: 'Send',
    messagePrepared: 'Message delivered',
    messagePreparedText: 'Your message has been delivered successfully, we will process it as soon as possible, thank you.',
    pageNotFound: 'Page not found',
    pageNotFoundText: 'This page does not exist or was moved.',
    backHome: 'Back home',
    footerText:
      'Your destination for the best phones, accessories and gadgets in El Eulma.',
    navigation: 'Navigation',
    quickLinks: 'Quick links',
    products: 'Products',
    rights: '2026 The Phone. All rights reserved.',
    deliveryTitle: 'Delivery',
    deliveryText: 'Fast delivery across Algeria',
    location: 'Location',
    supportClient: 'Customer support',
    securePayment: 'Secure payment',
    securePaymentText: 'Reliable transactions and order tracking',
    adminTitle: 'Admin dashboard',
    adminSubtitle: 'Manage products, promotions and store statistics.',
    adminLogin: 'Admin login',
    adminLoginText: 'Restricted access for store management.',
    username: 'Username',
    password: 'Password',
    login: 'Login',
    logout: 'Logout',
    invalidCredentials: 'Invalid credentials',
    signedIn: 'Signed in',
    backToStore: 'View store',
    adminEssential: 'Back office',
    charts: 'Visual statistics',
    categoryDistribution: 'Products by category',
    promotionShare: 'Promotion status',
    uploadImage: 'Upload image',
    uploadSecondImage: 'Upload image 2',
    activePromos: 'Active promos',
    normalProducts: 'Standard products',
    totalProducts: 'Products',
    promoProducts: 'Promotions',
    categoriesStat: 'Categories',
    inventoryValue: 'Catalog value',
    productManager: 'Product manager',
    addProduct: 'Add product',
    updateProduct: 'Update product',
    resetForm: 'Reset',
    brand: 'Brand',
    category: 'Category',
    price: 'Price',
    rating: 'Rating',
    image: 'Image',
    secondImage: 'Image 2',
    description: 'Description',
    isNew: 'New',
    isPromo: 'Promotion',
    discount: 'Discount %',
    actions: 'Actions',
    edit: 'Edit',
    promo: 'Promo',
    productSaved: 'Product saved',
    productDeleted: 'Product deleted',
    confirmDeleteProduct: 'Delete this product?',
    confirmDeleteProductText: 'It will disappear from the public catalog.',
    promotionUpdated: 'Promotion updated',
    shareExperience: 'Share your experience',
    personalInfo: 'Personal Information',
    firstName: 'First Name',
    lastName: 'Last Name',
    phone: 'Phone',
    emailOptional: 'Email (optional)',
    shippingAddress: 'Shipping Address',
    wilaya: 'Wilaya',
    selectWilaya: 'Select a wilaya',
    baladiya: 'Commune (Baladiya)',
    selectBaladiya: 'Select a commune',
    fullAddress: 'Full Address',
    postalCode: 'Postal Code (optional)',
    orderDetails: 'Order Details',
    quantity: 'Quantity',
    additionalNotes: 'Additional Notes',
    placeOrder: 'Place Order',
    fieldRequired: 'This field is required',
    invalidPhone: 'Invalid phone number',
    invalidEmail: 'Invalid email address',
    orders: 'Orders',
    totalOrders: 'Total Orders',
    totalRevenue: 'Total Revenue',
    averageOrderValue: 'Average Order Value',
    pendingOrders: 'Pending Orders',
    ordersByWilaya: 'Orders by Wilaya',
    ordersByProduct: 'Orders by Product',
    monthlySales: 'Monthly Sales',
    orderStatusDistribution: 'Order Status Distribution',
    topSellingProducts: 'Top Selling Products',
    revenueByDay: 'Revenue by Day',
    searchOrders: 'Search orders...',
    status: 'Status',
    orderDate: 'Date',
    customer: 'Customer',
    allStatuses: 'All statuses',
    pending: 'Pending',
    validated: 'Validated',
    shipped: 'Shipped',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    orderId: 'Order ID',
    viewDetails: 'View details',
    close: 'Close',
    save: 'Save',
    noOrders: 'No orders found',
    noOrdersText: 'Adjust your filters or wait for new orders.',
    productStatus: 'Product Status',
    inStock: 'In stock',
    lowStock: 'Low stock',
    outOfStock: 'Out of stock',
    bulkDelete: 'Delete selection',
    deleteSelected: 'Delete selected',
    bulkPromo: 'Promo selection',
    sold: 'Sold',
    stock: 'Stock',
    dashboard: 'Dashboard',
    ordersTab: 'Orders',
    productsTab: 'Products',
    categoriesTab: 'Categories',
    feedbackTab: 'Feedback',
    contactsTab: 'Contacts',
    feedbackTitle: 'Feedback',
    feedbackSubtitle: 'Share your experience',
    sendFeedback: 'Send feedback',
    feedbackAdded: 'Feedback added',
    feedbackDeleted: 'Feedback deleted',
    feedbackThankYou: 'Thank you for sharing your opinion.',
    newCategory: 'New category',
    changeImage: 'Change image',
    visible: 'Visible',
    hidden: 'Hidden',
    categoryAdded: 'Category added',
    categorySaveFailed: 'Category save failed',
    categorySaveFailedText: 'Unable to save category to the backend.',
    deleteCategoryTitle: 'Delete this category?',
    deleteCategoryMessage: 'will be removed from the category list and from Our Products.',
    categoryDeleted: 'Category deleted',
    socialMedia: 'Social media',
    selectedProducts: 'products selected',
    bulkDeleteConfirm: 'You are about to delete',
    productsWord: 'products',
    bulkPromoMessage: 'products set to promo.',
    googleMapsLink: 'View on Google Maps',
    galleryImages: 'Image gallery',
    uploadGallery: 'Add images',
    maxGalleryImages: 'Maximum 7 additional images',
    removeImage: 'Remove image',
    contactMessages: 'Contact messages',
    unread: 'Unread',
    markAsRead: 'Mark as read',
    noContacts: 'No contact messages',
    noContactsText: 'No messages received yet.',
    contactDeleted: 'Contact deleted',
    totalMessages: 'Total messages',
    unreadMessages: 'Unread',
    readMessages: 'Read',
    productSaveError: 'Save error',
    productSaveErrorText: 'Unable to save product to the backend.',
    date: 'Date',
    findUsOnMap: 'Find us',
    processingText: 'Processing...',
    orderSuccessTitle: 'Thank you for your order!',
    orderSuccessMessage: 'Your order has been received successfully. We will call you shortly for confirmation. Thank you!',
    confirmDelete: 'Are you sure you want to delete',
    selected: 'selected',
    whatsappUs: 'WhatsApp',
    callUs: 'Call us',
    noCategoriesYet: 'No categories yet',
    color: 'Color',
    storage: 'Storage',
    colorPlaceholder: 'e.g. Black, White, Gold',
    storagePlaceholder: 'e.g. 128GB, 256GB, 512GB',
    swipeCategories: 'Swipe to see more categories',
    scrollCategoriesDesktop: 'Use the arrows to browse 3 categories at a time',
    scrollLeft: 'Scroll left',
    scrollRight: 'Scroll right',
    colorOptionsHint: 'Quick pick or add a custom value',
    storageOptionsHint: 'Quick pick or add a custom capacity',
    quickChoose: 'Quick choose',
    addCustomValue: 'Add',
    chooseOptions: 'Choose options',
    selectOptionsInCart: 'Please choose all options for each product',
    productOptions: 'Product options',
    addOptionGroup: 'Add option',
    optionNamePlaceholder: 'e.g. Color, Storage, RAM',
    optionValuesPlaceholder: 'Values separated by commas',
    selectAllOptions: 'Please select all options',
    selectedOptions: 'Selected options',
    removeOptionGroup: 'Remove',
    customOptionValues: 'Option values',
    decreaseQuantity: 'Decrease quantity',
    increaseQuantity: 'Increase quantity',
  },
  ar: {
    home: 'الرئيسية',
    shop: 'المتجر',
    about: 'من نحن',
    contact: 'اتصل بنا',
    admin: 'الإدارة',
    phones: 'الهواتف',
    accessories: 'الإكسسوارات',
    laptop: 'الحواسيب',
    searchPlaceholder: 'ابحث عن هاتف أو إكسسوار...',
    noSearchResults: 'لا توجد نتائج',
    viewAllResults: 'عرض كل النتائج',
    heroTitle: 'The Phone - الهواتف والإكسسوارات',
    heroText: 'هواتف أصلية، إكسسوارات مميزة وخدمة موثوقة في العلمة.',
    buy: 'تسوق الآن',
    moreInfo: 'معلومات أكثر',
    ourProducts: 'منتجاتنا',
    featured: 'منتجات مميزة',
    promotions: 'العروض',
    new: 'جديد',
    add: 'إضافة',
    addToCart: 'إضافة للسلة',
    addedToCart: 'تمت إضافة المنتج للسلة',
    addedToWishlist: 'تمت الإضافة للمفضلة',
    removedFromWishlist: 'تم الحذف من المفضلة',
    catalog: 'الكتالوج',
    catalogTitle: 'هواتف وإكسسوارات مميزة',
    productCount: 'منتج',
    searchProduct: 'ابحث عن منتج...',
    allCategories: 'كل التصنيفات',
    allBrands: 'كل العلامات',
    sortBy: 'ترتيب حسب',
    priceLowHigh: 'السعر: من الأقل للأعلى',
    priceHighLow: 'السعر: من الأعلى للأقل',
    noProducts: 'لم يتم العثور على منتجات',
    noProductsText: 'جرب بحثا آخر أو غير الفلاتر.',
    relatedProducts: 'منتجات مشابهة',
    productNotFound: 'المنتج غير موجود',
    backToCatalog: 'العودة للكتالوج',
    cart: 'السلة',
    cartEmpty: 'سلتك فارغة',
    cartEmptyText: 'أضف هواتفك وإكسسواراتك المفضلة.',
    viewCatalog: 'عرض الكتالوج',
    checkoutTitle: 'إتمام الطلب',
    clearCart: 'تفريغ السلة',
    summary: 'الملخص',
    subtotal: 'المجموع الفرعي',
    delivery: 'التوصيل',
    toConfirm: 'للتأكيد',
    total: 'الإجمالي',
    requestOrder: 'طلب الشراء',
    confirmClearTitle: 'تفريغ السلة؟',
    confirmClearMessage: 'سيتم حذف كل المنتجات من السلة.',
    confirmOrderTitle: 'تأكيد الطلب؟',
    confirmOrderMessage: 'هل تريد تأكيد هذا الطلب؟',
    orderCreated: 'تم إنشاء الطلب',
    orderCreatedMessage: 'تم تسجيل طلبك بنجاح.',
    confirmRemoveTitle: 'حذف هذا المنتج؟',
    remove: 'حذف',
    cancel: 'إلغاء',
    clearedCart: 'تم تفريغ السلة',
    removedProduct: 'تم حذف المنتج',
    wishlist: 'المفضلة',
    wishlistEmpty: 'لا توجد منتجات مفضلة بعد',
    wishlistEmptyText: 'احتفظ بمنتجاتك المفضلة هنا للوصول إليها بسرعة.',
    exploreProducts: 'استكشف المنتجات',
    wishlistTitle: 'اختياراتك',
    aboutTitle: 'متجرك الموثوق للهواتف',
    selectionPremium: 'اختيار ممتاز',
    selectionText:
      'The Phone يقدم هواتف وإكسسوارات ومنتجات مختارة للاستخدام اليومي بجودة عالية.',
    localBase: 'مقرنا في العلمة',
    localText: 'نرافق العملاء من العلمة بطريقة بسيطة ومباشرة ومحلية.',
    usefulAdvice: 'نصيحة شخصية',
    usefulAdviceText:
      'تحتاج مساعدة لاختيار موديل أو مواصفات؟ فريقنا يرشدك حسب ميزانيتك واحتياجاتك.',
    contactTitle: 'أخبرنا بما تحتاجه',
    address: 'العنوان',
    addressText: 'العلمة، الجزائر. التوصيل متاح حسب الطلب.',
    support: 'الدعم',
    supportText: 'دعم طوال الأسبوع للمنتجات والتوفر والطلبات.',
    quickRequest: 'طلب سريع',
    name: 'الاسم',
    phoneOrEmail: 'الهاتف أو البريد',
    message: 'رسالتك',
    send: 'إرسال',
    messagePrepared: 'تم تسليم الرسالة',
    messagePreparedText: 'تم تسليم رسالتك بنجاح، سنقوم بمعالجتها في أقرب وقت ممكن، شكرا.',
    pageNotFound: 'الصفحة غير موجودة',
    pageNotFoundText: 'هذه الصفحة غير موجودة أو تم نقلها.',
    backHome: 'العودة للرئيسية',
    footerText: 'وجهتك لأفضل الهواتف والإكسسوارات والمنتجات في العلمة.',
    navigation: 'التنقل',
    quickLinks: 'روابط سريعة',
    products: 'المنتجات',
    rights: '2026 The Phone. كل الحقوق محفوظة.',
    deliveryTitle: 'التوصيل',
    deliveryText: 'توصيل سريع في كل الجزائر',
    location: 'الموقع',
    supportClient: 'دعم العملاء',
    securePayment: 'دفع آمن',
    securePaymentText: 'معاملات موثوقة وتتبع الطلب',
    adminTitle: 'لوحة الإدارة',
    adminSubtitle: 'إدارة المنتجات والعروض وإحصائيات المتجر.',
    adminLogin: 'دخول الإدارة',
    adminLoginText: 'وصول مخصص لإدارة المتجر.',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    login: 'دخول',
    logout: 'خروج',
    invalidCredentials: 'بيانات الدخول غير صحيحة',
    signedIn: 'تم تسجيل الدخول',
    backToStore: 'عرض المتجر',
    adminEssential: 'لوحة التحكم',
    charts: 'إحصائيات مرئية',
    categoryDistribution: 'المنتجات حسب التصنيف',
    promotionShare: 'حالة العروض',
    uploadImage: 'رفع صورة',
    uploadSecondImage: 'رفع صورة 2',
    activePromos: 'عروض نشطة',
    normalProducts: 'منتجات عادية',
    totalProducts: 'المنتجات',
    promoProducts: 'العروض',
    categoriesStat: 'التصنيفات',
    inventoryValue: 'قيمة الكتالوج',
    productManager: 'إدارة المنتجات',
    addProduct: 'إضافة منتج',
    updateProduct: 'تحديث المنتج',
    resetForm: 'إعادة ضبط',
    brand: 'العلامة',
    category: 'التصنيف',
    price: 'السعر',
    rating: 'التقييم',
    image: 'الصورة',
    secondImage: 'الصورة 2',
    description: 'الوصف',
    isNew: 'جديد',
    isPromo: 'عرض',
    discount: 'التخفيض %',
    actions: 'إجراءات',
    edit: 'تعديل',
    promo: 'عرض',
    productSaved: 'تم حفظ المنتج',
    productDeleted: 'تم حذف المنتج',
    confirmDeleteProduct: 'حذف هذا المنتج؟',
    confirmDeleteProductText: 'سيختفي من الكتالوج العام.',
    promotionUpdated: 'تم تحديث العرض',
    shareExperience: 'شارك تجربتك',
    personalInfo: 'المعلومات الشخصية',
    firstName: 'الاسم الأول',
    lastName: 'اللقب',
    phone: 'رقم الهاتف',
    emailOptional: 'البريد الإلكتروني (اختياري)',
    shippingAddress: 'عنوان التوصيل',
    wilaya: 'الولاية',
    selectWilaya: 'اختر الولاية',
    baladiya: 'البلدية',
    selectBaladiya: 'اختر البلدية',
    fullAddress: 'العنوان الكامل',
    postalCode: 'الرمز البريدي (اختياري)',
    orderDetails: 'تفاصيل الطلب',
    quantity: 'الكمية',
    additionalNotes: 'ملاحظات إضافية',
    placeOrder: 'تأكيد الطلب',
    fieldRequired: 'هذا الحقل مطلوب',
    invalidPhone: 'رقم هاتف غير صالح',
    invalidEmail: 'بريد إلكتروني غير صالح',
    orders: 'الطلبات',
    totalOrders: 'إجمالي الطلبات',
    totalRevenue: 'إجمالي الدخل',
    averageOrderValue: 'متوسط قيمة الطلب',
    pendingOrders: 'طلبات قيد الانتظار',
    ordersByWilaya: 'الطلبات حسب الولاية',
    ordersByProduct: 'الطلبات حسب المنتج',
    monthlySales: 'المبيعات الشهرية',
    orderStatusDistribution: 'توزيع حالات الطلبات',
    topSellingProducts: 'المنتجات الأكثر مبيعاً',
    revenueByDay: 'الدخل اليومي',
    searchOrders: 'البحث في الطلبات...',
    status: 'الحالة',
    orderDate: 'التاريخ',
    customer: 'الزبون',
    allStatuses: 'كل الحالات',
    pending: 'قيد الانتظار',
    validated: 'مؤكد',
    shipped: 'تم الشحن',
    delivered: 'تم التوصيل',
    cancelled: 'ملغى',
    orderId: 'رقم الطلب',
    viewDetails: 'عرض التفاصيل',
    close: 'إغلاق',
    save: 'حفظ',
    noOrders: 'لم يتم العثور على طلبات',
    noOrdersText: 'قم بتغيير الفلاتر أو انتظر طلبات جديدة.',
    productStatus: 'حالة المنتج',
    inStock: 'متوفر',
    lowStock: 'كمية قليلة',
    outOfStock: 'نفد من المخزون',
    bulkDelete: 'حذف المحدد',
    deleteSelected: 'حذف المحدد',
    bulkPromo: 'تخفيض المحدد',
    sold: 'المبيعات',
    stock: 'المخزون',
    dashboard: 'لوحة المعلومات',
    ordersTab: 'الطلبات',
    productsTab: 'المنتجات',
    categoriesTab: 'التصنيفات',
    feedbackTab: 'التقييمات',
    contactsTab: 'الرسائل',
    feedbackTitle: 'التقييمات',
    feedbackSubtitle: 'شارك تجربتك',
    sendFeedback: 'إرسال التقييم',
    feedbackAdded: 'تم إضافة التقييم',
    feedbackDeleted: 'تم حذف التقييم',
    feedbackThankYou: 'شكراً لمشاركة رأيك.',
    newCategory: 'تصنيف جديد',
    changeImage: 'تغيير الصورة',
    visible: 'مرئي',
    hidden: 'مخفي',
    categoryAdded: 'تم إضافة التصنيف',
    categorySaveFailed: 'فشل حفظ التصنيف',
    categorySaveFailedText: 'تعذر حفظ التصنيف.',
    deleteCategoryTitle: 'حذف هذا التصنيف؟',
    deleteCategoryMessage: 'سيتم حذفه من القائمة ومن منتجاتنا.',
    categoryDeleted: 'تم حذف التصنيف',
    socialMedia: 'شبكات التواصل',
    selectedProducts: 'منتج محدد',
    bulkDeleteConfirm: 'سيتم حذف',
    productsWord: 'منتج',
    bulkPromoMessage: 'منتج تم وضعه في عرض.',
    googleMapsLink: 'عرض على خرائط جوجل',
    galleryImages: 'معرض الصور',
    uploadGallery: 'إضافة صور',
    maxGalleryImages: '7 صور إضافية كحد أقصى',
    removeImage: 'حذف الصورة',
    contactMessages: 'رسائل الاتصال',
    unread: 'غير مقروء',
    markAsRead: 'تعليم كمقروء',
    noContacts: 'لا توجد رسائل اتصال',
    noContactsText: 'لم يتم استلام أي رسائل بعد.',
    contactDeleted: 'تم حذف الرسالة',
    totalMessages: 'إجمالي الرسائل',
    unreadMessages: 'غير مقروءة',
    readMessages: 'مقروءة',
    productSaveError: 'خطأ في الحفظ',
    productSaveErrorText: 'تعذر حفظ المنتج.',
    date: 'التاريخ',
    findUsOnMap: 'موقعنا',
    processingText: 'جاري المعالجة...',
    orderSuccessTitle: 'شكراً لطلبك!',
    orderSuccessMessage: 'تم استلام طلبك بنجاح. سنتصل بك قريباً لتأكيد الطلب. شكراً لك!',
    confirmDelete: 'هل أنت متأكد من حذف',
    selected: 'محدد',
    whatsappUs: 'واتساب',
    callUs: 'اتصل بنا',
    noCategoriesYet: 'لا توجد تصنيفات بعد',
    color: 'اللون',
    storage: 'التخزين',
    colorPlaceholder: 'مثال: أسود، أبيض، ذهبي',
    storagePlaceholder: 'مثال: 128GB، 256GB، 512GB',
    swipeCategories: 'اسحب لرؤية المزيد من التصنيفات',
    scrollCategoriesDesktop: 'استخدم الأسهم لعرض 3 تصنيفات في كل مرة',
    scrollLeft: 'التمرير لليسار',
    scrollRight: 'التمرير لليمين',
    colorOptionsHint: 'اختر بسرعة أو أضف قيمة مخصصة',
    storageOptionsHint: 'اختر بسرعة أو أضف سعة مخصصة',
    quickChoose: 'اختيار سريع',
    addCustomValue: 'إضافة',
    chooseOptions: 'اختر الخيارات',
    selectOptionsInCart: 'يرجى اختيار جميع الخيارات لكل منتج',
    productOptions: 'خيارات المنتج',
    addOptionGroup: 'إضافة خيار',
    optionNamePlaceholder: 'مثال: اللون، التخزين، RAM',
    optionValuesPlaceholder: 'قيم مفصولة بفواصل',
    selectAllOptions: 'يرجى اختيار جميع الخيارات',
    selectedOptions: 'الخيارات المختارة',
    removeOptionGroup: 'حذف',
    customOptionValues: 'قيم الخيار',
    decreaseQuantity: 'تقليل الكمية',
    increaseQuantity: 'زيادة الكمية',
  },
};

const languages = [
  { code: 'fr', label: 'FR' },
  { code: 'en', label: 'EN' },
  { code: 'ar', label: 'AR' },
];

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => window.localStorage.getItem('ab-store-language') || 'fr'
  );

  useEffect(() => {
    window.localStorage.setItem('ab-store-language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const value = useMemo(
    () => ({
      dir: language === 'ar' ? 'rtl' : 'ltr',
      language,
      languages,
      setLanguage,
      t: (key) => dictionaries[language][key] || dictionaries.fr[key] || key,
    }),
    [language]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}
