spring.application.name=ab-store
server.port=8081
app.admin-reset-key=abdelbasetabstore
# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/abstore
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cloudinary Configuration (Replace with your actual keys)
cloudinary.cloud-name=doyhwx0l8
cloudinary.api-key=585176213351547
cloudinary.api-secret=7FwgRF-7hgiWRTd_i3Lt_de3tlQ

# Increase Multipart Upload Limits
spring.servlet.multipart.max-file-size=70MB
spring.servlet.multipart.max-request-size=70MB
